In [5]:
from keras import Sequential
from  keras.layers import Dense,SimpleRNN

In [6]:
model = Sequential()

model.add(SimpleRNN(
    32,
    input_shape=(10, 1)))


model.add(Dense(1, activation='sigmoid'))
model.summary()

C:\Users\hp\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [7]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(1, 32)


array([[-0.13332587, -0.03730345,  0.297172  ,  0.33591235,  0.38559747,
         0.24284405,  0.0643115 , -0.10256794,  0.17873478,  0.08081514,
         0.05070361, -0.03689539, -0.3166033 , -0.33894372,  0.12553012,
         0.0359723 ,  0.25699532, -0.33983144, -0.05947715, -0.3872763 ,
         0.25119925, -0.13899028,  0.11930108, -0.41621754,  0.13835996,
        -0.20364764, -0.2943629 ,  0.25224644,  0.3413443 , -0.08994323,
         0.03691715, -0.0490756 ]], dtype=float32)

In [8]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(32, 32)


array([[-0.09503508,  0.15566418, -0.11485966, ..., -0.08503043,
         0.08160119, -0.05076679],
       [ 0.30677503,  0.27423328, -0.1488277 , ...,  0.28782156,
        -0.18890096,  0.11768868],
       [-0.02630595,  0.00603532, -0.30599114, ..., -0.03478774,
        -0.1177664 ,  0.0379452 ],
       ...,
       [-0.10367039, -0.14778422,  0.05796778, ...,  0.08215806,
        -0.1773928 , -0.2198773 ],
       [-0.08682007,  0.20091861,  0.02207441, ..., -0.06804252,
         0.0374019 ,  0.03889074],
       [ 0.35919964, -0.1087299 , -0.19420138, ..., -0.0888773 ,
        -0.18097267, -0.11911596]], shape=(32, 32), dtype=float32)

In [9]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(32,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [10]:
print(model.get_weights()[3].shape)
model.get_weights()[3]

(32, 1)


array([[ 0.2603842 ],
       [ 0.21422976],
       [-0.03487486],
       [-0.40284473],
       [ 0.1618734 ],
       [ 0.04942319],
       [-0.15928608],
       [-0.18988322],
       [-0.16741976],
       [-0.08998615],
       [ 0.05165225],
       [ 0.17009175],
       [ 0.3197528 ],
       [ 0.4173715 ],
       [ 0.21300703],
       [-0.2457898 ],
       [-0.21108097],
       [ 0.42084032],
       [ 0.14841306],
       [-0.19097486],
       [ 0.18667483],
       [-0.00053361],
       [-0.20802175],
       [-0.33068135],
       [ 0.15460324],
       [-0.38654077],
       [ 0.26123816],
       [-0.0441083 ],
       [ 0.28513873],
       [ 0.12893224],
       [ 0.28753978],
       [-0.31028277]], dtype=float32)

In [11]:
print(model.get_weights()[4].shape)
model.get_weights()[4]

(1,)


array([0.], dtype=float32)

In [12]:
model = Sequential()

model.add(SimpleRNN(
    32,
    input_shape=(10, 1)))


model.add(Dense(1, activation='relu'))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(1, 32)


array([[ 3.6001205e-05, -3.2008868e-01, -2.2667490e-01,  1.6814119e-01,
        -3.0323821e-01, -5.6028396e-02, -2.4159878e-02,  1.3824105e-01,
         1.0933131e-02,  3.1660485e-01,  3.1937796e-01,  2.2654408e-01,
         1.4632267e-01, -1.7953636e-01, -1.3188523e-01,  1.8917423e-01,
        -2.0654227e-01, -2.2763957e-01,  4.4037133e-02,  3.0058259e-01,
         1.2071240e-01,  4.1989070e-01,  7.4357152e-02, -1.8151429e-01,
         3.9282733e-01,  1.8085366e-01,  2.0939112e-02,  6.5287948e-04,
        -2.1821558e-02,  1.3986802e-01, -2.4301341e-01, -9.8372757e-02]],
      dtype=float32)

In [14]:
model = Sequential()

model.add(SimpleRNN(
    32,
    input_shape=(10, 1)))


model.add(Dense(1, activation='tanh'))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)             │ (None, 32)                  │           1,088 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(1, 32)


array([[ 0.08045703,  0.38882738, -0.10178444,  0.34577763, -0.07948577,
        -0.14320001,  0.11853904, -0.10199487,  0.382083  ,  0.3713714 ,
         0.34997386,  0.30959696, -0.13870412,  0.06700584,  0.38343376,
         0.09011406,  0.39126223, -0.10594189,  0.08736843, -0.31897497,
        -0.42130676, -0.05455998, -0.02851507,  0.07786173,  0.3891033 ,
         0.24932623,  0.30105907,  0.27788615,  0.39641625, -0.23277514,
        -0.42273936, -0.10086113]], dtype=float32)

In [17]:
model.compile('adam','accuracy')

In [20]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [22]:
X_train.shape

(25000,)

In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv("dataset.csv")

In [5]:
df.head()

,text,label
0,Excellent product #287,1
1,Awesome app #145,1
2,Horrible work #512,0
3,I love this movie #359,1
4,Amazing experience #49,1


In [6]:
tokenizer = Tokenizer(num_words=5000)

tokenizer.fit_on_texts(df["text"])

X = tokenizer.texts_to_sequences(df["text"])

X = pad_sequences(X, maxlen=100)

y = df["label"]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [8]:
model = Sequential([

    Embedding(
        input_dim=5000,
        output_dim=128,
        input_length=100
    ),

    LSTM(64),

    Dense(32, activation="relu"),

    Dense(1, activation="sigmoid")

])

C:\Users\hp\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [10]:
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - accuracy: 0.7266 - loss: 0.6804 - val_accuracy: 0.6875 - val_loss: 0.6473
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.9563 - loss: 0.5095 - val_accuracy: 1.0000 - val_loss: 0.3247
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.1214 - val_accuracy: 1.0000 - val_loss: 0.0393
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 1.0000 - loss: 0.0149 - val_accuracy: 1.0000 - val_loss: 0.0063
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 1.0000 - loss: 0.0033 - val_accuracy: 1.0000 - val_loss: 0.0031
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 1.0000 - loss: 0.0018 - val_accuracy: 1.0000 - val_loss: 0.0020
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 0.0013 - val_accuracy: 1.0000 - val_loss: 0.0015
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 1.0000 - loss: 9.6240e-04 - val_accuracy: 1.0000

In [11]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 8.4501e-04 
Accuracy: 1.0


In [12]:
model.save("lstm_model.keras")

In [1]:
!git --version

git version 2.54.0.windows.1


In [3]:
!cd

C:\Users\hp\Deep_learning


In [5]:
!git init

Initialized empty Git repository in C:/Users/hp/Deep_learning/.git/


In [18]:
!git remote -v

origin	https://github.com/dishantpatidar2503/Deeplearning_RNN.git (fetch)
origin	https://github.com/dishantpatidar2503/Deeplearning_RNN.git (push)


In [19]:
!git push -u origin main

remote: warning: File train.zip is 50.32 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: error: Trace: 14c31e7d149666bb45034cf459503e29757b427d585fc176d5cdc51d80d68433        
remote: error: See https://gh.io/lfs for more information.        
remote: error: File cat_dog_model.h5 is 169.87 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
To https://github.com/dishantpatidar2503/Deeplearning_RNN.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/dishantpatidar2503/Deeplearning_RNN.git'


In [20]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is 1A3A-7913

 Directory of C:\Users\hp\Deep_learning

09-07-2026  09:18    <DIR>          .
09-07-2026  09:37    <DIR>          ..
15-06-2026  09:33    <DIR>          .ipynb_checkpoints
06-06-2026  11:10            13,805 api.ipynb
15-06-2026  10:51           244,361 Cats_vs_Dogs_CNN.ipynb
15-06-2026  10:43       178,116,856 cat_dog_model.h5
15-06-2026  10:22    <DIR>          clean_dataset
01-06-2026  18:01           228,886 D1.ipynb
15-06-2026  09:41    <DIR>          dataset
07-07-2026  19:08            23,623 dataset.csv
02-06-2026  10:34            23,873 diabetes.csv
04-06-2026  18:23         4,648,021 DSC_9021.JPG
06-06-2026  19:25            28,316 encoding.ipynb
03-06-2026  00:55            84,445 Hypertune.ipynb
04-06-2026  18:42             3,636 image.ipynb
07-07-2026  19:12         8,330,977 lstm_model.keras
03-06-2026  00:32    <DIR>          mydir
02-06-2026  23:21    <DIR>          my_dir
09-07-2026  09:18         

In [21]:
!git rm --cached cat_dog_model.h5
!git rm --cached train.zip

rm 'cat_dog_model.h5'
rm 'train.zip'


In [22]:
!git add .
!git commit -m "Remove large files"

[main 405947e] Remove large files
 1 file changed, 13 insertions(+), 4039 deletions(-)


In [23]:
!git log --oneline --all

405947e Remove large files
160d2da Add RNN notebook
783b911 Initial commit


In [24]:
!rmdir /s /q .git

In [25]:
!dir /a

 Volume in drive C has no label.
 Volume Serial Number is 1A3A-7913

 Directory of C:\Users\hp\Deep_learning

09-07-2026  09:49    <DIR>          .
09-07-2026  09:37    <DIR>          ..
15-06-2026  09:33    <DIR>          .ipynb_checkpoints
06-06-2026  11:10            13,805 api.ipynb
15-06-2026  10:51           244,361 Cats_vs_Dogs_CNN.ipynb
15-06-2026  10:43       178,116,856 cat_dog_model.h5
15-06-2026  10:22    <DIR>          clean_dataset
01-06-2026  18:01           228,886 D1.ipynb
15-06-2026  09:41    <DIR>          dataset
07-07-2026  19:08            23,623 dataset.csv
02-06-2026  10:34            23,873 diabetes.csv
04-06-2026  18:23         4,648,021 DSC_9021.JPG
06-06-2026  19:25            28,316 encoding.ipynb
03-06-2026  00:55            84,445 Hypertune.ipynb
04-06-2026  18:42             3,636 image.ipynb
07-07-2026  19:12         8,330,977 lstm_model.keras
03-06-2026  00:32    <DIR>          mydir
02-06-2026  23:21    <DIR>          my_dir
09-07-2026  09:48         

In [26]:
!git init

Initialized empty Git repository in C:/Users/hp/Deep_learning/.git/


In [27]:
!git add RNN.ipynb

In [1]:
!git commit -m "RNN_model"

On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   RNN.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Cats_vs_Dogs_CNN.ipynb
	D1.ipynb
	DSC_9021.JPG
	Hypertune.ipynb
	api.ipynb
	cat_dog_model.h5
	clean_dataset/
	dataset.csv
	dataset/
	diabetes.csv
	encoding.ipynb
	image.ipynb
	lstm_model.keras
	mydir/
	test.zip
	train.zip
	untitled_project/

no changes added to commit (use "git add" and/or "git commit -a")
